ALTER TABLE "SONGS" ADD CONSTRAINT "SONGS_fk0" FOREIGN KEY ("album_id") REFERENCES "ALBUMS"("albumID");

ALTER TABLE "ALBUMS" ADD CONSTRAINT "ALBUMS_fk0" FOREIGN KEY ("artist_id") REFERENCES "ARTISTS"("artistID");


CREATE INDEX artist_id ON "ALBUMS" (artist_id);
CREATE INDEX album_id ON "SONGS" (album_id);